[build]
  command = "pnpm build --filter @acme/web"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Redirect all to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200