CREATE TABLE users.ads (
	id serial4 NOT NULL,
	url varchar NOT NULL,
	address varchar NOT NULL,
	price int4 NOT NULL,
	rooms int2 NOT NULL,
	"views" int2 NULL,
	created_at timestamp DEFAULT now() NOT NULL,
	updated_at timestamp DEFAULT now() NOT NULL,
	flat_id int4 DEFAULT 1 NOT NULL,
	total_area numeric(5, 2) NULL,
	living_area numeric(5, 2) NULL,
	kitchen_area numeric(5, 2) NULL,
	floor int2 NULL,
	total_floors int2 NULL,
	bathroom varchar(100) NULL,
	balcony varchar(100) NULL,
	renovation varchar(100) NULL,
	furniture varchar(100) NULL,
	construction_year int2 NULL,
	house_type varchar(100) NULL,
	ceiling_height numeric(3, 2) NULL,
	metro_station varchar(100) NULL,
	metro_time varchar(100) NULL,
	tags text NULL,
	description text NULL,
	photo_urls _text NULL,
	"source" int2 NULL,
	status varchar(100) NULL,
	views_today int2 NULL,
	total_views int4 NULL,
	CONSTRAINT ads_pkey PRIMARY KEY (id))